## Práctica de Python y Pandas

El objetivo de esta práctica es aplicar la sintaxis básica de Python, así como también poder utilizar el análisis de datos con Pandas.

### Parte I - Fundamentos de Python

In [8]:
# Ejercicio 1: Clasificación de edad

def clasificar_edad(edad):
    if edad < 13:
        return "Niño"
    elif edad <= 17:
        return "Adolescente"
    elif edad <= 59:
        return "Adulto"
    else:
        return "Adulto mayor"

edad = 21
categoria = clasificar_edad(edad)
print(f"Edad: {edad} años")
print(f"Categoría: {categoria}")

Edad: 21 años
Categoría: Adulto

In [9]:
# Ejercicio 2: Conversor de temperatura

In [10]:
# Ejercicio 3: Calculadora básica

num1 = float(input("Introduce el primer número: "))
num2 = float(input("Introduce el segundo número: "))

print("\nOperaciones permitidas: +, -, *, /")
operacion = input("Introduce el símbolo de la operación: ")

if operacion == "+":
    resultado = num1 + num2
    print(f"\nResultado: {num1} + {num2} = {resultado}")

elif operacion == "-":
    resultado = num1 - num2
    print(f"\nResultado: {num1} - {num2} = {resultado}")

elif operacion == "*":
    resultado = num1 * num2
    print(f"\nResultado: {num1} * {num2} = {resultado}")

elif operacion == "/":
    if num2 == 0:
        print("\nError: No se puede dividir entre cero.")
    else:
        resultado = num1 / num2
        print(f"\nResultado: {num1} / {num2} = {resultado}")

else:
    print("\nError: Operación no válida.")

Operaciones permitidas: +, -, *, /

Resultado: 14.0 + 55.0 = 69.0

In [11]:
# Ejercicio 4: Número par o impar

numero = int(input("Introduce un número entero: "))

if numero % 2 == 0:
    print(f"El número {numero} es PAR.")
else:
    print(f"El número {numero} es IMPAR.")

El número 8 es PAR.

In [12]:
# Ejercicio 5: Tabla de multiplicar

numero = 7

print(f"Tabla de multiplicar del {numero}:")
for i in range(1, 13):
    print(f"  {numero} x {i} = {numero * i}")

Tabla de multiplicar del 7:
  7 x 1 = 7
  7 x 2 = 14
  7 x 3 = 21
  7 x 4 = 28
  7 x 5 = 35
  7 x 6 = 42
  7 x 7 = 49
  7 x 8 = 56
  7 x 9 = 63
  7 x 10 = 70
  7 x 11 = 77
  7 x 12 = 84

In [13]:
# Ejercicio  6: Contador de vocales

frase = "La practica hace al maestroo"
vocales = "aeiou"
contador = 0

for letra in frase.lower():
    if letra in vocales:
        contador += 1

print(f"Frase: {frase}")
print(f"Cantidad de vocales: {contador}")

Frase: La practica hace al maestroo
Cantidad de vocales: 11

In [14]:
# Ejercicio 7: Promedio de calificaciones

calificaciones = [85, 72, 90, 68, 77]

total = sum(calificaciones)
promedio = total / len(calificaciones)

print(f"Calificaciones: {calificaciones}")
print(f"Suma total: {total}")
print(f"Promedio: {promedio:.1f}")

if promedio >= 70:
    print("Estado: Aprobado")
else:
    print("Estado: Reprobado")

Calificaciones: [85, 72, 90, 68, 77]
Suma total: 392
Promedio: 78.4
Estado: Aprobado

In [15]:
# Ejercicio 8: Lista de números positivos y negativos

In [16]:
# Ejercicio 9: Mayor y menor de una lista

In [17]:
# Ejercicio 10: Diccionario de estudiante

### Parte II - Funciones, listas y estructuras

In [18]:
# Ejercicio 11: Función para calcular descuento

In [28]:
# Ejercicio 12: Validación de contraseña

contrasena = "Segura123"

tiene_longitud = len(contrasena) >= 8
tiene_numero = any(c.isdigit() for c in contrasena)
tiene_mayuscula = any(c.isupper() for c in contrasena)
tiene_minuscula = any(c.islower() for c in contrasena)

print(f"Contrasena: {contrasena}")
print(f"  Longitud minima (8): {tiene_longitud}")
print(f"  Contiene numero: {tiene_numero}")
print(f"  Contiene mayuscula: {tiene_mayuscula}")
print(f"  Contiene minuscula: {tiene_minuscula}")

if tiene_longitud and tiene_numero and tiene_mayuscula and tiene_minuscula:
    print("Resultado: Contrasena VALIDA")
else:
    print("Resultado: Contrasena NO valida")

Contrasena: Segura123
  Longitud minima (8): True
  Contiene numero: True
  Contiene mayuscula: True
  Contiene minuscula: True
Resultado: Contrasena VALIDA

In [20]:
# Ejercicio 13: Sistema simple de inventario

In [21]:
# Ejercicio 14: Registro de ventas

In [22]:
# Ejercicio 15: Limpieza básica de texto

frase_original = "   Hola  esto   es una frase de   prueba con   muchos espacios   "
print(f"Frase original: '{frase_original}'\n")

frase_limpia = frase_original.strip()

frase_limpia = frase_limpia.lower()

while "  " in frase_limpia:
    frase_limpia = frase_limpia.replace("  ", " ")

print(f"Frase limpia:   '{frase_limpia}'")

palabras = frase_limpia.split(" ")
total_palabras = len(palabras)
print(f"Número total de palabras: {total_palabras}\n")

print("="*60)
print("EXPLICACIÓN DE LOS MÉTODOS UTILIZADOS:")
print("="*60)
print("- strip(): Elimina todos los caracteres de espacio en blanco (espacios, pestañas, saltos de línea)")
print("           que se encuentren al principio (izquierda) y al final (derecha) de la cadena de texto.")
print("- lower(): Convierte todos los caracteres alfabéticos con mayúsculas de la cadena a minúsculas.")
print("- replace(antiguo, nuevo): Busca una subcadena específica dentro del texto y la reemplaza")
print("                           por otra subcadena nueva todas las veces que aparezca.")
print("- split(separador): Divide una cadena de texto en una lista de subcadenas basándose en un")
print("                    carácter separador especificado (por defecto es cualquier espacio en blanco).")

Frase original: '   Hola  esto   es una frase de   prueba con   muchos espacios   '

Frase limpia:   'hola esto es una frase de prueba con muchos espacios'
Número total de palabras: 10

============================================================
EXPLICACIÓN DE LOS MÉTODOS UTILIZADOS:
============================================================
- strip(): Elimina todos los caracteres de espacio en blanco (espacios, pestañas, saltos de línea)
           que se encuentren al principio (izquierda) y al final (derecha) de la cadena de texto.
- lower(): Convierte todos los caracteres alfabéticos con mayúsculas de la cadena a minúsculas.
- replace(antiguo, nuevo): Busca una subcadena específica dentro del texto y la reemplaza
                           por otra subcadena nueva todas las veces que aparezca.
- split(separador): Divide una cadena de texto en una lista de subcadenas basándose en un
                    carácter separador especificado (por defecto es cualquier espacio en blanco).

### Parte III - Ejercicios aplicando pandas

In [23]:
# Ejercicio 16: DataFrame de estudiantes

import pandas as pd

datos_estudiantes = {
    'nombre': ['Carlos', 'Ana', 'Luis', 'Sofia', 'Fernando', 'Maria', 'Jorge', 'Elena', 'Ricardo', 'Beatriz'],
    'carrera': ['Sistemas', 'Medicina', 'Sistemas', 'Derecho', 'Industrial', 'Medicina', 'Sistemas', 'Derecho', 'Industrial', 'Sistemas'],
    'edad': [21, 23, 20, 22, 24, 21, 22, 20, 25, 23],
    'promedio': [85.5, 92.0, 78.0, 88.5, 65.0, 90.0, 81.5, 74.0, 89.0, 95.5],
    'ciudad': ['Tegucigalpa', 'San Pedro Sula', 'Tegucigalpa', 'La Ceiba', 'Choluteca', 'San Pedro Sula', 'Comayagua', 'Tegucigalpa', 'La Ceiba', 'Santa Rosa']
}

df = pd.DataFrame(datos_estudiantes)

print("--- 3. Muestre las primeras 5 filas ---")
display(df.head(5)) 

print("\n--- 4. Muestre la información general del DataFrame ---")
df.info()

print("\n--- 5. Calcule el promedio general de calificaciones ---")
promedio_general = df['promedio'].mean()
print(f"El promedio general de todos los estudiantes es: {promedio_general:.2f}")

print("\n--- 6. Muestre estudiantes con promedio mayor o igual a 80 ---")
estudiantes_altos = df[df['promedio'] >= 80]
display(estudiantes_altos)

print("\n--- 7. Ordene estudiantes por promedio de mayor a menor ---")
df_ordenado = df.sort_values(by='promedio', ascending=False)
display(df_ordenado)

--- 3. Muestre las primeras 5 filas ---

     nombre     carrera  edad  promedio          ciudad
0    Carlos    Sistemas    21      85.5     Tegucigalpa
1       Ana    Medicina    23      92.0  San Pedro Sula
2      Luis    Sistemas    20      78.0     Tegucigalpa
3     Sofia     Derecho    22      88.5        La Ceiba
4  Fernando  Industrial    24      65.0       Choluteca

--- 4. Muestre la información general del DataFrame ---
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   nombre    10 non-null     str
 1   carrera   10 non-null     str
 2   edad      10 non-null     int64
 3   promedio  10 non-null     float64
 4   ciudad    10 non-null     str
dtypes: float64(1), int64(1), str(3)
memory usage: 532.0 bytes

--- 5. Calcule el promedio general de calificaciones ---
El promedio general de todos los estudiantes es: 83.90

--- 6. Muestre estudiantes con promedio mayor o igual a 80 ---

    nombre     carrera  edad  promedio          ciudad
0   Carlos    Sistemas    21      85.5     Tegucigalpa
1      Ana    Medicina    23      92.0  San Pedro Sula
3    Sofia     Derecho    22      88.5        La Ceiba
5    Maria    Medicina    21      90.0  San Pedro Sula
6    Jorge    Sistemas    22      81.5       Comayagua
8  Ricardo  Industrial    25      89.0        La Ceiba
9  Beatriz    Sistemas    23      95.5      Santa Rosa

--- 7. Ordene estudiantes por promedio de mayor a menor ---

     nombre     carrera  edad  promedio          ciudad
9   Beatriz    Sistemas    23      95.5      Santa Rosa
1       Ana    Medicina    23      92.0  San Pedro Sula
5     Maria    Medicina    21      90.0  San Pedro Sula
8   Ricardo  Industrial    25      89.0        La Ceiba
3     Sofia     Derecho    22      88.5        La Ceiba
0    Carlos    Sistemas    21      85.5     Tegucigalpa
6     Jorge    Sistemas    22      81.5       Comayagua
2      Luis    Sistemas    20      78.0     Tegucigalpa
7     Elena     Derecho    20      74.0     Tegucigalpa
4  Fernando  Industrial    24      65.0       Choluteca

In [24]:
# Ejercicio 17: Análisis de ventas con pandas

In [25]:
# Ejercicio 18: Limpieza de datos con pandas

In [26]:
# Ejercicio 19: Análisis de préstamos

In [27]:
# Ejercicio 20: Mini análisis de datos tipo empresa

### Conclusión personal sobre lo aprendido